
import { Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

const balooBhai = Baloo_Bhai_2({
  subsets: ["latin"],
  display: "swap",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${balooBhai.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
